name: Setup Project
description: Install dependencies and set up Node.js
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - run: npm ci
